# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"